### ISSUE TITLE
Download doesn't run in Mojave

### ISSUE THREAD

**Issue by boourns** [vgorloff/AUHost#19]
When I download the latest release and copy it to /Applications, and run, it crashes instantly.  Looks like it doesn't meet code signing expectations.

```
Process:               AUHost [6623]
Path:                  /Applications/AUHost.app/Contents/MacOS/AUHost
Identifier:            ua.com.wavelabs.AUHost
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           AUHost [6623]
User ID:               501

Date/Time:             2019-05-13 09:12:35.630 -0400
OS Version:            Mac OS X 10.14.4 (18E226)
Report Version:        12
Anonymous UUID:        98DB7BC2-5898-D8B5-E565-AF20127D4C8D

Sleep/Wake UUID:       C8B65A1E-88A2-4F81-A4D7-81A1BFBF2173

Time Awake Since Boot: 23000 seconds
Time Since Wake:       3800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):

```

I would build it myself however I'm having trouble with the ruby steps:
```
unzip -q "/Users/tom/Code/Swift/AUHost/Vendor/WL/Scripts/Proxy/mcAutomation.framework.zip" -d "/Users/tom/Code/Swift/AUHost/Vendor/WL/Scripts/Proxy"
/Users/tom/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/ffi-1.10.0/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/Users/tom/Code/Swift/AUHost/Vendor/WL/Scripts/Proxy/mcAutomation.framework/mcAutomation': dlopen(/Users/tom/Code/Swift/AUHost/Vendor/WL/Scripts/Proxy/mcAutomation.framework/mcAutomation, 5): Symbol not found: _$SBOSgXwWV (LoadError)
  Referenced from: /Users/tom/Code/Swift/AUHost/Vendor/WL/Scripts/Proxy/mcAutomation.framework/Versions/A/Frameworks/mcTypes.framework/Versions/A/mcTypes
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Users/tom/Code/Swift/AUHost/Vendor/WL/Scripts/Proxy/mcAutomation.framework/Versions/A/Frameworks/mcTypes.framework/Versions/A/mcTypes
	from /Users/tom/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/ffi-1.10.0/lib/ffi/library.rb:99:in `map'
	from /Users/tom/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/ffi-1.10.0/lib/ffi/library.rb:99:in `ffi_lib'
	from /Users/tom/Code/Swift/AUHost/Vendor/WL/Scripts/Proxy/AutomationProxy.rb:25:in `<module:AutomationProxy>'
	from /Users/tom/Code/Swift/AUHost/Vendor/WL/Scripts/Proxy/AutomationProxy.rb:22:in `<top (required)>'
	from /Users/tom/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/tom/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/tom/Code/Swift/AUHost/Project.rb:5:in `block in <top (required)>'
	from /Users/tom/Code/Swift/AUHost/Project.rb:5:in `each'
	from /Users/tom/Code/Swift/AUHost/Project.rb:5:in `<top (required)>'
	from /Users/tom/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/tom/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Command PhaseScriptExecution failed with a nonzero exit code
```

Any help you can provide would be appreciated.  I'm getting frustrated just trying to set up a sane audio unit program / run / debug cycle! (which I am not blaming you for ;) )

Cheers,
Tom

**Comment by vgorloff** [comment]
Hello Tom,

The issue in automation code. It is "over engineered" and now outdated. I will replace that old version and will make new Release.

**Comment by vgorloff** [comment]
Should be fixed in https://github.com/vgorloff/AUHost/releases/tag/1.1.12.

**Comment by boourns** [comment]
Looks fixed to me, thanks!

**Comment by vgorloff** [comment]
FYI: Release https://github.com/vgorloff/AUHost/releases/tag/1.1.13 fixes broken Plug-In registration due missed `Extension.entitlements` file.
